---
# general tasks
- name: set pg1 hostname
  hostname:
    use: systemd
    name: "{{ pg1_hostname }}"
  run_once: true
  delegate_to: "{{ groups['postgresql-local'][0] }}"

- name: set pg2 hostname
  hostname:
    use: systemd
    name: "{{ pg2_hostname }}"
  run_once: true
  delegate_to: "{{ groups['postgresql'][0] }}"

- name: set pg3 hostname
  hostname:
    use: systemd
    name: "{{ pg3_hostname }}"
  run_once: true
  delegate_to: "{{ groups['postgresql'][1] }}"

- name: update /etc/hosts
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} Postgresql servers"
    block: |
      {{ pg1_priv1 }} {{ pg1_hostname }} pg1
      {{ pg2_priv1 }} {{ pg2_hostname }} pg2
      {{ pg3_priv1 }} {{ pg3_hostname }} pg3

- name: importing signing key for repo
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
    
- name: adding postgresql repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt bullseye-pgdg main 
    filename: pgdg
    state: present

- name: updating repos
  apt:
    update_cache: yes

- name: installing postgresql-14 and repmgrd packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - postgresql-14 
    - postgresql-14-repmgr
